### ISSUE TITLE
Unable to update inner source

### ISSUE THREAD

**Issue by Freyskeyd** [netvl/xml-rs#145]
Hello,

I'm trying to feed a `Cursor<Vec<u8>>` after `EventReader` creation:

```rust
let mut v:Vec<u8> = String::from("<mydoc >").into_bytes();
let mut buff:Cursor<Vec<u8>> = Cursor::new(v);

let mut stream = EventReader::new(buff);
let current_buff = stream.source().get_ref().clone();

let closing = "</mydoc>".as_bytes();
let b = [&current_buff[..], &closing[..]].concat();

stream.source_mut().write_all(&b);
stream.source_mut().flush();

println!("root: {:?}", str::from_utf8(stream.source().get_ref()));

loop {
    match stream.next() {
        Ok(x) => {
            println!("OK {:?}", x);
            match x {
                e => {}
            }
        },
        Err(e) => panic!("{:?}", e)
    };
}
```

it's yieling:

```
root: Ok("<mydoc ></mydoc>")
thread 'test_trailing_bytes' panicked at 'Error { pos: 1:1, kind: Syntax("Unexpected end of stream: no root element found") }', tests/test_basic.rs:357
```

Am I doing something wrong or I miss something in the documentation?

**Comment by netvl** [comment]
This is quite natural. The `Cursor` type has only one "position", used both for reading and writing. What happens in your case is that you first create a cursor out of a string `<mydoc >`, and the position inside it points to the beginning:
```
<mydoc >
^
```
Then you write to it a joined array of its current content and another string, `</mydoc>`, overwriting its initial contents (although the overwritten part remains the same, obviously), and putting the cursor after the end of the written data:
```
<mydoc ></mydoc>
                ^
```

Then you attempt to read from the cursor without resetting its position. Since it points after the end of all of the data you have written, the next read will naturally return an EOF, which is exactly what the error is about: an unexpected end of stream.

To make your example work, before reading from the stream reset the cursor position to the beginning. This can be done using the `Seek` trait or simply by calling the `set_position` method on the cursor, right after you wrote the data:

```
stream.source_mut().write_all(&b);
stream.source_mut().flush();
stream.source_mut().set_position(0);
```

Then your code will not panic anymore, although it will go to an infinite loop because `stream.next()`, when the parser reaches the end of the document, will return `XmlEvent::EndDocument` infinitely. It is better to use the iterator interface, it handles this situation and will terminate after the parser reaches the end of the document.

The following code works for me:
```rust
extern crate xml;

use std::io::{Cursor, Write};
use std::str;

use xml::EventReader;

fn main() {
    let mut v: Vec<u8> = String::from("<mydoc >").into_bytes();
    let mut buff: Cursor<Vec<u8>> = Cursor::new(v);

    let mut stream = EventReader::new(buff);
    let current_buff = stream.source().get_ref().clone();

    let closing = "</mydoc>".as_bytes();
    let b = [&current_buff[..], &closing[..]].concat();

    stream.source_mut().write_all(&b);
    stream.source_mut().flush();
    stream.source_mut().set_position(0);

    println!("root: {:?}", str::from_utf8(stream.source().get_ref()));

    loop {
        match stream.next() {
            Ok(x) => {
                println!("OK {:?}", x);
                match x {
                    xml::reader::XmlEvent::EndDocument => break,
                    e => {}
                }
            },
            Err(e) => panic!("{:?}", e)
        };
    }
}
```
and it prints the following:
```
root: Ok("<mydoc ></mydoc>")
OK StartDocument(1.0, UTF-8, None)
OK StartElement(mydoc, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
OK EndElement(mydoc)
OK EndDocument
```

As a general note, it is a bad idea to modify the underlying stream of the parser. Here you do it before parsing, so it kind of turns out to be okay (after the aforementioned fix), but if you do it after the parsing has started, you are very likely to screw up the parsing process and get weird errors. I definitely don't recommend doing it.

**Comment by Freyskeyd** [comment]
Well, how can I deal with feeding the source after EventReader creation? :/

**Comment by netvl** [comment]
As I said, this is probably not a good idea in general. However, with some care I think you can make it work.

One way would be to try and find some kind of `Cursor` with two independent positions, for reading and for writing. Then you can write the stream and then read it again through the `EventReader` without much hassle. It is quite possible that there is such thing on crates.io, or you can write one yourself.

Alternatively, you probably can use `Cursor`, but then before each writing operation you will have to remember the current cursor position and then restore it right after you finished the writing and before you attempt to parse the next part of the document. This should be done very carefully, but I think it can be made to work.

**Comment by Freyskeyd** [comment]
@netvl I implement a struct that implement Read an hold my buffer :)
It's working for now.
