### ISSUE TITLE
end-of-line in attribute

### ISSUE THREAD

**Issue by mettke** [netvl/xml-rs#153]
In the Readme.md you said "attribute value normalization is not performed, and end-of-line characters are not normalized too.". Is there a reason why end-of-line characters are not normalized and is there a way to manually write the normalized form without disabling normalization completely?

The Problem I'm facing is that I have to create an XML which contains an attribute like this:
```
testOp()&#xA;after
```
("\&#xA;" is the normalized Version of a "\n")

Reading a file is not a Problem as the Parser correctly normalizes it to "\n". 
Writing it on the other hands leads either to a newline in the file when using "\n" (as it is not getting normalized) or to "\&amp;#xA;" using "\&#xA;" (cause the & is being normalized).

**Comment by netvl** [comment]
The reason is that I tried to implement the writer as quickly as possible and therefore some functionality is not present simply because I didn't get to it yet. For now, the only way would be to preprocess the value manually before passing it to the writer.

Unfortunately, I'm currently very busy because of a long-term business trip, so I don't know when I will be able to do this. I don't think it is hard to do (if I remember correctly, it is a matter of creating just another escaping function and executing it before writing the attribute value to the output), so I would welcome any contributions :)

**Comment by mettke** [comment]
Awesome that's the answer I was hoping for. Changes upcoming.
